### PR TITLE
Switch to v3 API

### PR DESCRIPTION
**Pull request by holm**
I tried to keep everything as close to what it was, only changing what was needed to support v3.

This is a V3-only alternative to https://github.com/gotschmarcel/nodemailer-sendinblue-transport/pull/3

### CODE REVIEW

**Comment by akosasante** [comment]
Any chance that this will be merged? Currently the V2 endpoints are set to be shutdown in Nov 2022: https://developers.sendinblue.com/docs/apiv2-sunset-roadmap#september-november

@gotschmarcel

**Comment by gotschmarcel** [comment]
I‘ll take a look later this week this.

**Comment by gotschmarcel** [comment]
I can take merge this, but this package hasn't been updated for ages. So I will merge it, but also introduce some modernizations and more recent dependencies.

**Comment by gotschmarcel** [comment]
Can you please fix the tests and linting errors. Run `npm run test` for testing & `npm run prepublish` for linting. Please squash your commits.

**Comment by gotschmarcel** [comment]
V3 support and several code modernisations were merged to `dev` branch.

**Comment by gotschmarcel** [comment]
Version 2.0.0 is out with support for v3 & templates.

**Comment by akosasante** [comment]
Thank you, much appreciated!

**Pull request closed without merging**
