### PR TITLE
ref: Refactor to brevo, instead of sendinblue, due to re-branding of …

### PR DESCRIPTION
**Pull request by circles-00**
Refactor to brevo, instead of sendinblue, due to re-branding of sendinblue

### CODE REVIEW

**Review by gotschmarcel — APPROVED** [review]

**Comment by circles-00** [comment]
Hey @gotschmarcel, I know you merged this, but to republish it on npm under this new name of the package, I will need to remove my package from npm, since I published it under the new name. Please let me know if you want me to remove it so you can publish it.

Cheers!

**Comment by gotschmarcel** [comment]
Hey! First of all, thank you for the PR - much appreciated. I'm planning on publishing it today. I would appreciate if you remove your fork from NPM.

**Comment by circles-00** [comment]
No problem man, always happy to help the community. The fork should be deleted now and you should be able to publish it under this name. If any issues, please contact me.

**Comment by gotschmarcel** [comment]
Thanks a lot! Have a nice day :)

**Comment by gotschmarcel** [comment]
@circles-00 It seems that I can't republish this today. I'll try again tomorrow. It's probably forbidden because you only recently removed the package.

**Comment by circles-00** [comment]
Hey I'm reading the NPM docs and it says that you need to wait for 24 hours after deleting the package. So, it should work tomorrow!

**Comment by gotschmarcel** [comment]
Exactly, what I just found as well. I'll do it tomorrow then.

**Comment by gotschmarcel** [comment]
Just letting you know that I was able to publish it.

**Pull request merged**
